name: package
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  enough_ascii_art: ^1.1.0
  image: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
